param([string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,[string]$OutputPath = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')).Path 'catalog/schema_catalog.json'))
$ErrorActionPreference = 'Stop'
$items=@()
foreach($root in @('registries','schemas')){ $dir=Join-Path $RepoRoot $root; Get-ChildItem $dir -Recurse -Filter '*.json' | Sort-Object FullName | ForEach-Object { $j=Get-Content $_.FullName -Raw|ConvertFrom-Json; $rel=[IO.Path]::GetRelativePath($RepoRoot,$_.FullName).Replace('\','/'); $items += [ordered]@{artifact_id=$j.artifact_id;artifact_kind=$j.artifact_kind;artifact_version=$j.artifact_version;projection_status=$j.projection_status;path=$rel;trace_object_type=$j.x_trace_object_type;id_field=$j.x_id_field;normative_owners=@($j.normative_owners);dependencies=@()} } }
$blocked=@()
$blocked += [ordered]@{artifact_id='schema.legal_classification_assessment';artifact_kind='json_schema';artifact_version='0.1.0';projection_status='BLOCKED_BY_OWNER';path=$null;trace_object_type='LEGAL CLASSIFICATION ASSESSMENT';id_field='LEGAL CLASSIFICATION ASSESSMENT ID';normative_owners=@([ordered]@{document='GOVERNANCE/LEGAL_RESEARCH_METHOD_v1.md';version='v0.2';sections=@('§8');role='dependency'});dependencies=@('CLASSIFICATION LIKELIHOOD REGISTRY owner approval/freeze')}
$blocked += [ordered]@{artifact_id='schema.module_screening_record';artifact_kind='json_schema';artifact_version='0.1.0';projection_status='BLOCKED_BY_OWNER';path=$null;trace_object_type='MODULE SCREENING RECORD';id_field='MODULE SCREENING RECORD ID';normative_owners=@([ordered]@{document='GOVERNANCE/REQUIREMENTS_MATRIX_GOVERNANCE_v1.md';version='v0.3';sections=@('§5.1');role='dependency'});dependencies=@('approved module trigger model')}
$blocked += [ordered]@{artifact_id='schema.module_trigger_set';artifact_kind='json_schema';artifact_version='0.1.0';projection_status='BLOCKED_BY_OWNER';path=$null;trace_object_type='MODULE TRIGGER SET';id_field='TRIGGER SET ID';normative_owners=@([ordered]@{document='GOVERNANCE/MODULE_TRIGGER_REGISTRY_v1.md';version='v0.1';sections=@('§2');role='dependency'});dependencies=@('trigger owners approved')}
$blocked += [ordered]@{artifact_id='schema.source_record';artifact_kind='json_schema';artifact_version='0.1.0';projection_status='BLOCKED_BY_OWNER';path=$null;trace_object_type='SOURCE';id_field='SOURCE ID';normative_owners=@([ordered]@{document='GOVERNANCE/AI_TOOL_USAGE_POLICY_v1.md';version='unapproved';sections=@('DATA CLASS REGISTRY');role='dependency'});dependencies=@('DATA CLASS registry approved/frozen')}
$blocked += [ordered]@{artifact_id='schema.data_class_event';artifact_kind='json_schema';artifact_version='0.1.0';projection_status='BLOCKED_BY_OWNER';path=$null;trace_object_type='DATA CLASS EVENT';id_field='EVENT ID';normative_owners=@([ordered]@{document='GOVERNANCE/AI_TOOL_USAGE_POLICY_v1.md';version='unapproved';sections=@('DATA CLASS REGISTRY');role='dependency'});dependencies=@('DATA CLASS registry approved/frozen')}
$blocked += [ordered]@{artifact_id='schema.output_record';artifact_kind='json_schema';artifact_version='0.1.0';projection_status='BLOCKED_BY_OWNER';path=$null;trace_object_type='OUTPUT';id_field='OUTPUT ID';normative_owners=@([ordered]@{document='GOVERNANCE/OPERATION_WORKFLOWS_v1.md';version='v0.2';sections=@('OUTPUT TYPE REGISTRY');role='dependency'});dependencies=@('OUTPUT TYPE registry approved/frozen')}
$items += $blocked
$out=[ordered]@{catalog_version='0.1.0';generated_from='WS1 artefact metadata + explicit BLOCKED_BY_OWNER dependencies';entries=@($items|Sort-Object artifact_id)}
$json=$out|ConvertTo-Json -Depth 12
$dir=Split-Path $OutputPath -Parent;if($dir -and -not(Test-Path $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null}
[IO.File]::WriteAllText($OutputPath,$json+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))
Write-Output ('WS1 catalog generated: '+$OutputPath)
