param([string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path,[string]$OutputPath=(Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')).Path 'catalog/schema_catalog.json'))
$ErrorActionPreference='Stop'
function J([string]$p){Get-Content (Join-Path $RepoRoot $p)-Raw|ConvertFrom-Json}
function B{return @{operation='registry.operation';object='registry.object';contract_type='registry.contract_type';module='registry.module';module_status='registry.module_status';applicability_authority='registry.applicability_authority';requirement_level='registry.requirement_level';governance_status='registry.governance_status';requirement_type='registry.requirement_type';requirement_status='registry.requirement_status';verification_level='registry.verification_level';resulting_verification_level='registry.verification_level';decision_type='registry.human_decision_type';suspension_state='registry.suspension_state';verification_methods='registry.verification_method';result='registry.verification_result';source_type='registry.source_type';content_hash_algorithm='registry.content_hash_algorithm';permission_status='registry.permission_status';trace_object_type='registry.trace_object_types'}}
function D($x,[string]$raw){$d=New-Object System.Collections.Generic.HashSet[string];$b=B;if($x.properties){foreach($p in $x.properties.PSObject.Properties){if($b.ContainsKey($p.Name)){[void]$d.Add($b[$p.Name])}}};foreach($m in [regex]::Matches($raw,'"\$ref"\s*:\s*"([^"]+)"')){$u=$m.Groups[1].Value;if($u-match'^urn:legal-verification-system:(.+)$'){[void]$d.Add($Matches[1])}};@($d|Sort-Object)}
$items=@()
foreach($root in @('registries','schemas')){Get-ChildItem (Join-Path $RepoRoot $root)-Recurse-Filter '*.json'|Sort-Object FullName|ForEach-Object{$raw=Get-Content $_.FullName-Raw;$x=$raw|ConvertFrom-Json;$rel=[IO.Path]::GetRelativePath($RepoRoot,$_.FullName).Replace('\','/');$items+=[ordered]@{artifact_id=$x.artifact_id;artifact_kind=$x.artifact_kind;artifact_version=$x.artifact_version;projection_status=$x.projection_status;path=$rel;trace_object_type=$x.x_trace_object_type;id_field=$x.x_id_field;normative_owners=@($x.normative_owners);missing_owner_dependencies=@();dependencies=@(D $x $raw)}}}
$br=J 'registries/blocked_dependencies.registry.json'
foreach($x in $br.entries){$items+=[ordered]@{artifact_id=$x.artifact_id;artifact_kind=$x.artifact_kind;artifact_version=$x.artifact_version;projection_status=$x.projection_status;path=$null;trace_object_type=$x.trace_object_type;id_field=$x.id_field;normative_owners=@($x.normative_owners);missing_owner_dependencies=@($x.missing_owner_dependencies);dependencies=@($x.activation_condition)}}
$out=[ordered]@{catalog_version='0.2.0';generated_from='WS1 artefact metadata + registries/blocked_dependencies.registry.json';entries=@($items|Sort-Object artifact_id)}
$json=$out|ConvertTo-Json-Depth 20;$dir=Split-Path $OutputPath-Parent;if($dir-and-not(Test-Path $dir)){New-Item-ItemType Directory-Path $dir-Force|Out-Null};[IO.File]::WriteAllText($OutputPath,$json+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))
