param([string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path)
$ErrorActionPreference='Stop';$fail=@();function Fail([string]$m){$script:fail+=$m};function J([string]$p){Get-Content (Join-Path $RepoRoot $p)-Raw|ConvertFrom-Json}
$rf=Get-ChildItem (Join-Path $RepoRoot 'registries') -Recurse -Filter '*.json';$sf=Get-ChildItem (Join-Path $RepoRoot 'schemas') -Recurse -Filter '*.json';$ids=@{}
foreach($f in @($rf)+@($sf)){try{$j=Get-Content $f.FullName -Raw|ConvertFrom-Json}catch{Fail('Invalid JSON '+$f.FullName);continue};foreach($k in @('artifact_id','artifact_version','artifact_kind','projection_status','normative_owners')){if($null -eq $j.$k){Fail('Missing metadata '+$k+' in '+$f.Name)}};if($j.projection_status -ne 'ACTIVE_PROJECTION'){Fail('Non-active executable '+$f.Name)};if($ids.ContainsKey($j.artifact_id)){Fail('Duplicate artifact_id '+$j.artifact_id)}else{$ids[$j.artifact_id]=$f.FullName}}
$types=J 'registries/traceability/trace_object_types.registry.json';$prefix=J 'registries/traceability/id_prefixes.registry.json';$map=J 'registries/traceability/trace_object_id_fields.registry.json';if(@($types.entries).Count-ne 19){Fail('TRACE OBJECT TYPE count')};if(@($prefix.entries).Count-ne 19){Fail('ID PREFIX count')};if(@($map.entries).Count-ne 19){Fail('mapping count')}
$tc=@($types.entries|ForEach-Object canonical);foreach($m in $map.entries){$p=@($prefix.entries|Where-Object trace_object_type -eq $m.trace_object_type);if($p.Count-ne 1 -or $p[0].prefix-ne $m.id_prefix){Fail('mapping/prefix '+$m.trace_object_type)};if($tc-notcontains $m.trace_object_type){Fail('mapping/type '+$m.trace_object_type)};$op=Join-Path $RepoRoot $m.owner_document;if(-not(Test-Path $op)){Fail('owner missing '+$m.owner_document)}else{$t=Get-Content $op-Raw;if($t-notmatch [regex]::Escape($m.id_field_name)){Fail('owner id field missing '+$m.id_field_name)}}}
$te=Get-Content (Join-Path $RepoRoot 'GOVERNANCE/TERMINOLOGY_AND_ENUMS_v1_v0.4.md')-Raw;$ps=Get-Content (Join-Path $RepoRoot 'GOVERNANCE/PROFESSIONAL_SCOPE_v1.4.md')-Raw;$tr=Get-Content (Join-Path $RepoRoot 'GOVERNANCE/TRACEABILITY_RECORD_v1_v0.6.md')-Raw;$vp=Get-Content (Join-Path $RepoRoot 'GOVERNANCE/VERIFICATION_PROTOCOL_v1.md')-Raw
foreach($e in $types.entries){if($te-notmatch [regex]::Escape($e.canonical) -or $te-notmatch [regex]::Escape($e.machine_key)){Fail('T&E trace type drift '+$e.canonical)}};foreach($e in $prefix.entries){if($te-notmatch [regex]::Escape($e.trace_object_type) -or $te-notmatch [regex]::Escape($e.prefix)){Fail('T&E prefix drift '+$e.trace_object_type)}}
$semantic=@('registry.operation','registry.object','registry.module','registry.requirement_status','registry.verification_level','registry.requirement_level','registry.governance_status','registry.requirement_type','registry.module_status','registry.applicability_authority','registry.cif_status','registry.permission_status','registry.suspension_state');foreach($f in $rf){$j=Get-Content $f.FullName-Raw|ConvertFrom-Json;foreach($e in @($j.entries)){if($e.canonical -and $e.machine_key){$ot=if($semantic-contains $j.artifact_id){$ps+$te}elseif($j.artifact_id-like 'registry.verification_*'){$vp}else{$te+$tr};if($ot-notmatch [regex]::Escape([string]$e.canonical)){Fail('owner canonical missing '+$j.artifact_id+' '+$e.canonical)};if($ot-notmatch [regex]::Escape([string]$e.machine_key)){Fail('owner machine key missing '+$j.artifact_id+' '+$e.machine_key)}}}}
$rr=Get-Content (Join-Path $RepoRoot 'schemas/traceability/trace_object_reference.schema.json')-Raw;foreach($n in @('trace_record_id','record_version','trace_object_type','trace_object_id','current','latest','oneOf')){if($rr-notmatch [regex]::Escape($n)){Fail('reference token '+$n)}};if($tr-notmatch 'INTRA-RECORD REFERENCE' -or $tr-notmatch 'CROSS-RECORD REFERENCE'){Fail('TR reference modes')};if($te-notmatch 'INTRA-RECORD REFERENCE' -or $te-notmatch 'CROSS-RECORD REFERENCE'){Fail('T&E reference modes')}
foreach($f in $sf){$j=Get-Content $f.FullName-Raw|ConvertFrom-Json;if($j.x_trace_object_type){$m=@($map.entries|Where-Object trace_object_type -eq $j.x_trace_object_type);if($m.Count-ne 1){Fail('schema mapping '+$j.artifact_id)}else{$snake=$m[0].id_field_name.ToLower().Replace(' ','_');if($j.x_id_field-ne $snake){Fail('schema id metadata '+$j.artifact_id)};if($null-eq $j.properties.$snake){Fail('schema id property '+$j.artifact_id)}}}}
foreach($pair in @(@('GOVERNANCE/TRACEABILITY_RECORD_v1_v0.6.md','GOVERNANCE/TRACEABILITY_RECORD_v1.md'),@('GOVERNANCE/TERMINOLOGY_AND_ENUMS_v1_v0.4.md','GOVERNANCE/TERMINOLOGY_AND_ENUMS_v1.md'))){if((Get-FileHash (Join-Path $RepoRoot $pair[0])).Hash-ne(Get-FileHash (Join-Path $RepoRoot $pair[1])).Hash){Fail('frozen alias drift '+$pair[0])}}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('ws1-'+[guid]::NewGuid().ToString()+'.json');& (Join-Path $RepoRoot 'TOOLS/build_ws1_catalog.ps1') -RepoRoot $RepoRoot -OutputPath $tmp|Out-Null;$a=(Get-Content (Join-Path $RepoRoot 'catalog/schema_catalog.json')-Raw|ConvertFrom-Json)|ConvertTo-Json -Depth 12 -Compress;$b=(Get-Content $tmp-Raw|ConvertFrom-Json)|ConvertTo-Json -Depth 12 -Compress;Remove-Item $tmp -Force;if($a-ne$b){Fail('catalog not reproducible')};$cat=J 'catalog/schema_catalog.json';foreach($x in @($cat.entries|Where-Object projection_status -eq 'BLOCKED_BY_OWNER')){if($null-ne$x.path){Fail('blocked path '+$x.artifact_id)}}
function TF([string]$n,[bool]$expect){$x=J ('TOOLS/fixtures/ws1/'+$n+'/fixture.json');$ok=$true;if((@($x.artifact_ids)|Sort-Object -Unique).Count-ne@($x.artifact_ids).Count){$ok=$false};$mapped=@($x.mapping|ForEach-Object trace_object_type);foreach($t in @($x.types)){if($mapped-notcontains$t){$ok=$false}};$targets=@($x.objects|ForEach-Object id);foreach($r in @($x.references)){if($targets-notcontains$r.target_id){$ok=$false}};if($ok-ne$expect){Fail('fixture '+$n)}};TF 'valid_projection' $true;TF 'invalid_duplicate_id' $false;TF 'invalid_missing_mapping' $false;TF 'invalid_unresolved_ref' $false
$frozen=@('GOVERNANCE/PROFESSIONAL_SCOPE_v1.4.md','GOVERNANCE/TRACEABILITY_RECORD_v1_v0.6.md','GOVERNANCE/TERMINOLOGY_AND_ENUMS_v1_v0.4.md','GOVERNANCE/VERIFICATION_PROTOCOL_v1.md');$changed=&git -C $RepoRoot diff --name-only HEAD^ HEAD -- @frozen;if($LASTEXITCODE-ne0){Fail('frozen diff check failed')};if($changed){Fail('frozen owner changed '+($changed-join','))}
if($fail.Count){$fail|ForEach-Object{Write-Error $_};exit 1};Write-Output 'WS1 CONTRACT LAYER VALIDATION: PASS'
